# "Numpy for deep learning"
> "A numpy cheat sheet for deep learning"
- toc: true
- branch: master
- badges: true
- comments: true
- categories: [jupyter, numpy, cheat_sheet]
#- image: images/ner_corona.png
- hide: false
- search_exclude: true

good resources:
* http://jalammar.github.io/visual-numpy/
* https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

## creating arrays

In [3]:
import numpy as np

In [6]:
a = np.array([1,2,3])
print(a)
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
print(b)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)
print(c)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [23]:
print("Create an array of zeros")
print(np.zeros((3,4))) 

print("Create an array of ones")
print(np.ones((2,3,4),dtype=np.int16)) 

print("Create an array of evenly spaced values (step value)")
d = np.arange(10,25,5)
print(d)

print("Create an array of evenly spaced values (number of samples)")
print(np.linspace(0,2,9)) 
print("Create a constant array")
e = np.full((2,2),7) #Create a constant array
print(e)


print("Create a 2X2 identity matrix")
f = np.eye(2) #Create a 2X2 identity matrix
print(f)

print("Create an array with random values")
print(np.random.random((2,2))) 
print("Create an empty array")
print(np.empty((3,2))) 

Create an array of zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Create an array of ones
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
Create an array of evenly spaced values (step value)
[10 15 20]
Create an array of evenly spaced values (number of samples)
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
Create a constant array
[[7 7]
 [7 7]]
Create a 2X2 identity matrix
[[1. 0.]
 [0. 1.]]
Create an array with random values
[[0.73813557 0.06780851]
 [0.86976112 0.03119131]]
Create an empty array
[[1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]]


## Data types

In [28]:
print("Signed 64-bit integer types")
print(np.int64) 

print("Standard double-precision floating point")
print(np.float32) 

print(" Complex numbers represented by 128 floats")
print(np.complex)

print("Boolean type storing TRUE and FALSE values")
print(np.bool)

print("Python object type")
print(np.object) 

print("Fixed-length string type")
print("np.string_")


print("Fixed-length unicode type")
print("np.unicode_")

Signed 64-bit integer types
<class 'numpy.int64'> 


Standard double-precision floating point
<class 'numpy.float32'> 


 Complex numbers represented by 128 floats
<class 'complex'> 


Boolean type storing TRUE and FALSE values
<class 'bool'> 


Python object type
<class 'object'> 


Fixed-length string type
np.string_ 


Fixed-length unicode type
np.unicode_ 


