# "Numpy for deep learning"
> "A numpy cheat sheet for deep learning"
- toc: true
- branch: master
- badges: true
- comments: true
- categories: [jupyter, numpy, cheat_sheet]
#- image: images/ner_corona.png
- hide: false
- search_exclude: true

good resources:
* http://jalammar.github.io/visual-numpy/
* https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

## Creating arrays

In [30]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [43]:
a = np.array([1,2,3])
a
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)
c

array([1, 2, 3])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [33]:
print("Create an array of zeros")
np.zeros((3,4))

print("Create an array of ones")
np.ones((2,3,4),dtype=np.int16)

print("Create an array of evenly spaced values (step value)")
d = np.arange(10,25,5)
d

print("Create an array of evenly spaced values (number of samples)")
np.linspace(0,2,9)
print("Create a constant array")
e = np.full((2,2),7) #Create a constant array
e


print("Create a 2X2 identity matrix")
f = np.eye(2) #Create a 2X2 identity matrix
f

print("Create an array with random values")
np.random.random((2,2))
print("Create an empty array")
print(np.empty((3,2))) 

Create an array of zeros


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Create an array of ones


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

Create an array of evenly spaced values (step value)


array([10, 15, 20])

Create an array of evenly spaced values (number of samples)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

Create a constant array


array([[7, 7],
       [7, 7]])

Create a 2X2 identity matrix


array([[1., 0.],
       [0., 1.]])

Create an array with random values


array([[0.05761588, 0.07959129],
       [0.78026783, 0.83792369]])

Create an empty array
[[1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]]


## Data types

In [34]:
print("Signed 64-bit integer types")
np.int64

print("Standard double-precision floating point")
np.float32

print(" Complex numbers represented by 128 floats")
np.complex

print("Boolean type storing TRUE and FALSE values")
np.bool

print("Python object type")
np.object

print("Fixed-length string type")
np.string_


print("Fixed-length unicode type")
np.unicode_

Signed 64-bit integer types


numpy.int64

Standard double-precision floating point


numpy.float32

 Complex numbers represented by 128 floats


complex

Boolean type storing TRUE and FALSE values


bool

Python object type


object

Fixed-length string type


numpy.bytes_

Fixed-length unicode type


numpy.str_

## Inspecting arrays

In [35]:
print("Array dimensions") 
a.shape 

print("Length of array")
len(a)

print("Number of array dimensions")
b.ndim 

print("Number of array elements")
e.size 

print("Data type of array elements")
b.dtype 

print("Name of data type")
b.dtype.name

print("Convert an array to a different type")
b.astype(int) 

Array dimensions


(3,)

Length of array


3

Number of array dimensions


2

Number of array elements


4

Data type of array elements


dtype('float64')

Name of data type


'float64'

Convert an array to a different type


array([[1, 2, 3],
       [4, 5, 6]])

## Artithmetric operations

In [40]:
print("Subtraction")
g = a - b 

np.subtract(a,b)

print("Addition")
b + a 

np.add(b,a)

print("Division")
a / b 

np.divide(a,b)

print("Multiplication")
a * b
np.multiply(a,b)

print("Exponentiation")
np.exp(b) 

print("Square root")
np.sqrt(b) 

print("Print sines of an array")
np.sin(a) 

print("Element-wise cosine")
np.cos(b) 

print("Element-wise natural logarithm")
np.log(a) 

print("Dot product")
e.dot(f) 


Subtraction


array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

Addition


array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

Division


array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

Multiplication


array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

Exponentiation


array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

Square root


array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Print sines of an array


array([0.84147098, 0.90929743, 0.14112001])

Element-wise cosine


array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

Element-wise natural logarithm


array([0.        , 0.69314718, 1.09861229])

Dot product


array([[7., 7.],
       [7., 7.]])

## Comparison

In [41]:
print("Element-wise comparison")
a == b 

print("Element-wise comparison")
a < 2 

print("Array-wise comparison")
np.array_equal(a, b) 

Element-wise comparison


array([[False,  True,  True],
       [False, False, False]])

Element-wise comparison


array([ True, False, False])

Array-wise comparison


False

## Aggregations


In [46]:
print("Array-wise sum")
a.sum() 

print("Array-wise minimum value")
a.min() 

print("Maximum value of an array row")
b.max(axis=0) 

print("Cumulative sum of the elements")
b.cumsum(axis=1) 

print("Mean")
a.mean() 

print("Median")
np.median(b)

print("Correlation coefficient")
np.corrcoef(a) 

print("Standard deviation")
np.std(b) 

Array-wise sum


6

Array-wise minimum value


1

Maximum value of an array row


array([4., 5., 6.])

Cumulative sum of the elements


array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

Mean


2.0

Median


3.5

Correlation coefficient


1.0

Standard deviation


1.5920810978785667

In [48]:
print("Create a view of the array with the same data")
h = a.view() 

print("Create a copy of the array")
np.copy(a) 

print("Create a deep copy of the array")
h = a.copy() 

Create a view of the array with the same data
Create a copy of the array


array([1, 2, 3])

Create a deep copy of the array
